# Generated by Django 6.0.2 on 2026-02-23 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='Mod Team', max_length=200, verbose_name='Название команды')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='О команде')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Логотип')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('mods_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во модов')),
                ('members_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во участников')),
                ('vk_group', models.URLField(blank=True, verbose_name='VK группа')),
                ('discord_server', models.URLField(blank=True, verbose_name='Discord сервер')),
                ('github_org', models.URLField(blank=True, verbose_name='GitHub организация')),
            ],
            options={
                'verbose_name': 'Страница «О нас»',
                'verbose_name_plural': 'Страница «О нас»',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='Обложка')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя / Ник')),
                ('role', models.CharField(choices=[('leader', 'Руководитель'), ('developer', 'Разработчик'), ('artist', 'Художник'), ('writer', 'Сценарист'), ('tester', 'Тестировщик'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Роль')),
                ('custom_role', models.CharField(blank=True, max_length=100, verbose_name='Своя роль')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team/avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK')),
                ('discord', models.CharField(blank=True, max_length=100, verbose_name='Discord')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команды',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Название ссылки')),
                ('url', models.URLField(verbose_name='URL')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='modteam.newspost', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='modteam.newspost', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
